server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
#    username: cos
#    password: cos1234

spring:

  h2:
    console:
      enabled: true 
      path: /h2-console
      
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver    
    username: user
    password: 1111

  jpa:
   database-platform: org.hibernate.dialect.H2Dialect   
   hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   show-sql: true
   defer-datasource-initialization : true  #ddl-auto 를 실행후 data.sql 또는 schema.sql 을 실행
      
   
     
logging:
  level:
    '[me.slivernine]': DEBUG
    

            
jwt:
  header: Authorization
  secret : c2laserfetesatesfsaertjksehtjekhkjnjterXERSETESRFfskejhteale324239u80vcasereekhkjnjterXERSETESRFfskejhteale3242
  token-validity-in-seconds: 86400
  



     
     
     