INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES(1, 'admin', '$2a$10$5C.vwUSuUH5G.LgdUICiKuL6pe6VXQQrbsGaOA2eWCik1fSCgbS8K' , '관리자', TRUE);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES(1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES(1, 'ROLE_ADMIN');