INSERT INTO USERS(USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES(1, 'admin', '111' , '관리자', TRUE);

INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES(1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID,AUTHORITY_NAME) VALUES(1, 'ROLE_ADMIN');